spring.application.name=data

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:usapresidents}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:mein_sicheres_passwort}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=none
