spring.application.name=data

# H2 Web Console configuration
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# In-memory database configuration
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Initialization settings for schema.sql and data.sql
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=none

# Allow non-local browser access to the H2 console inside Docker
spring.h2.console.settings.web-allow-others=true
