spring.application.name=data

# Activation et accès à la console Web H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuration de la base de données en mémoire
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Forcer l'exécution des fichiers schema.sql et data.sql au démarrage
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=none
